### ISSUE TITLE
Build of release  v5.0.4.0 is broken

### ISSUE THREAD

**Issue by pranasblk** [jalian-systems/marathonv5#1]
``
$ ./gradlew build
``

``
/Users/pranas/work/marathonv5/marathon-core/src/main/java/net/sourceforge/marathon/fx/display/ResultPane.java:189: error: refresh() has private access in TableView
            resultTable.refresh();
                       ^
/Users/pranas/work/marathonv5/marathon-core/src/main/java/net/sourceforge/marathon/fx/display/ResultPane.java:201: error: refresh() has private access in TableView
        resultTable.refresh();
                   ^
/Users/pranas/work/marathonv5/marathon-core/src/main/java/net/sourceforge/marathon/fx/display/LogView.java:99: error: refresh() has private access in TableView
            logTable.refresh();
                    ^
/Users/pranas/work/marathonv5/marathon-core/src/main/java/net/sourceforge/marathon/fx/display/LogView.java:115: error: refresh() has private access in TableView
            logTable.refresh();
                    ^
/Users/pranas/work/marathonv5/marathon-core/src/main/java/net/sourceforge/marathon/fx/display/LogView.java:131: error: refresh() has private access in TableView
            logTable.refresh();
                    ^
/Users/pranas/work/marathonv5/marathon-core/src/main/java/net/sourceforge/marathon/fx/display/LogView.java:233: error: refresh() has private access in TableView
        logTable.refresh();
                ^
/Users/pranas/work/marathonv5/marathon-core/src/main/java/net/sourceforge/marathon/fx/display/LogView.java:239: error: refresh() has private access in TableView
        logTable.refresh();
                ^
/Users/pranas/work/marathonv5/marathon-core/src/main/java/net/sourceforge/marathon/testrunner/fxui/TestRunner.java:95: error: cannot find symbol
                    testTree.refresh();
                            ^
  symbol:   method refresh()
  location: variable testTree of type TreeView<Test>
/Users/pranas/work/marathonv5/marathon-core/src/main/java/net/sourceforge/marathon/testrunner/fxui/TestRunner.java:111: error: cannot find symbol
            testTree.refresh();
                    ^
  symbol:   method refresh()
  location: variable testTree of type TreeView<Test>
/Users/pranas/work/marathonv5/marathon-core/src/main/java/net/sourceforge/marathon/testrunner/fxui/TestRunner.java:119: error: cannot find symbol
            testTree.refresh();
                    ^
  symbol:   method refresh()
  location: variable testTree of type TreeView<Test>
/Users/pranas/work/marathonv5/marathon-core/src/main/java/net/sourceforge/marathon/testrunner/fxui/TestRunner.java:131: error: cannot find symbol
            testTree.refresh();
                    ^
  symbol:   method refresh()
  location: variable testTree of type TreeView<Test>
/Users/pranas/work/marathonv5/marathon-core/src/main/java/net/sourceforge/marathon/testrunner/fxui/TestRunner.java:338: error: cannot find symbol
                testTree.refresh();
                        ^
  symbol:   method refresh()
  location: variable testTree of type TreeView<Test>
/Users/pranas/work/marathonv5/marathon-core/src/main/java/net/sourceforge/marathon/testrunner/fxui/TestRunner.java:509: error: cannot find symbol
        testTree.refresh();
                ^
  symbol:   method refresh()
  location: variable testTree of type TreeView<Test>
/Users/pranas/work/marathonv5/marathon-core/src/main/java/net/sourceforge/marathon/testrunner/fxui/TestRunner.java:676: error: cannot find symbol
        testTree.refresh();
                ^
  symbol:   method refresh()
  location: variable testTree of type TreeView<Test>
/Users/pranas/work/marathonv5/marathon-core/src/main/java/net/sourceforge/marathon/testrunner/fxui/TestRunner.java:770: error: cannot find symbol
        testTree.refresh();
                ^
  symbol:   method refresh()
  location: variable testTree of type TreeView<Test>
/Users/pranas/work/marathonv5/marathon-core/src/main/java/net/sourceforge/marathon/fx/display/FunctionStage.java:195: error: cannot find symbol
        tree.refresh();
            ^
  symbol:   method refresh()
  location: variable tree of type TreeView<Object>
/Users/pranas/work/marathonv5/marathon-core/src/main/java/net/sourceforge/marathon/fx/projectselection/ProjectSelection.java:246: error: refresh() has private access in TableView
            projectInfotable.refresh();
                            ^
17 errors
:marathon-core:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':marathon-core:compileJava'.
``

**Comment by kdmurthy** [comment]
Please check your JDK version.  Marathon requires JDK 1.8 and I recommend to use the latest release.

**Comment by pranasblk** [comment]
uname -a
Darwin Imin.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)

I think Marathon 5.0 code is broken due to JavaFX changes in recent JDK. The JavaFX component.refresh() is now private ...

The binary build run-time errors:
``
Error injecting constructor, java.lang.IllegalAccessError: tried to access method javafx.scene.control.TableView.refresh()V from class net.sourceforge.marathon.fx.display.LogView
  at net.sourceforge.marathon.fx.display.LogView.<init>(LogView.java:73)
  while locating net.sourceforge.marathon.fx.display.LogView
    for field at net.sourceforge.marathon.display.DisplayWindow.logView(DisplayWindow.java:198)
  while locating net.sourceforge.marathon.display.DisplayWindow
``

**Comment by kdmurthy** [comment]
Try with 1.8.0_121. We use u111 and u121 internally, so anyone should work.

-- KD


-- KD

--
Dakshinamurthy Karra
CEO & Managing Director
Jalian Systems Pvt. Ltd.
1st Floor, #457, 3rd Cross
5th Main, 5th Block
H.B.R Layout
Bangalore - 560043
INDIA
W: http://www.jaliansystems.com
W: http://www.marathontesting.com

**Comment by pranasblk** [comment]
Thanks, it works with the newest released jdk.
