### ISSUE TITLE
Marathon-java-recorder does support only JDK1.6?

### ISSUE THREAD

**Issue by niyas-git** [jalian-systems/marathonv5#13]
While running the gradle build, it is prompting to use the JDK1.6 for Marathon-java-agent and Marathon-java-recorder.
Can I upgrade the java versions to JDK1.7?  Will it support the same functionality.
Please clarify this.

**Comment by ck-aditya** [comment]
You can set the jdk6home to jdk1.8 or 1.7 in gradle properties and build the project.
Ensure that JAVA_HOME is set to 1.8 as for compiling JavaFX it is needed.
It should support the same functionality as there won't be any code change in Marathon.

**Comment by weixvfeng** [comment]
Marathon java-agent and java-recorder needs to be compiled with JDK6. Please set jdk6home property.

I have this problem when I build the project. Can you tell me how to solve this problem.

**Comment by ck-aditya** [comment]
You need to define jdk6home variable in the gradle.properties file in your .gradle home folder. 
Please refer the following link for further help.
[Gradle Properties](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties)
