### ISSUE TITLE
Unrecognized Java VM options

### ISSUE THREAD

**Issue by stefanspelitz** [jalian-systems/marathonv5#20]
The following VM arguments are not accepted
- `--upgrade-module-path`
- `--add-exports`
- `--add-opens`

when using the `Java Command Line Launcher` and setting `Java Home` within the application to AdoptOpen JDK 11.09.101 or Oracle JRE 9.0.4.

Using any of these VM arguments results in an error message like this:
```
Unrecognized option: --add-exports <the value>
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

I'm starting the marathon GUI application with a Java 8 JRE, since it won't run with Java 9 or higher.
My expectation would be that I can use the new VM arguments introduced in Java 9 with the corresponding target VM.

Is it possible to specify these VM arguments for my application under test?

**Comment by kdmurthy** [comment]
You need to use JDK 8 only to launch marathon. You can use any other jdk for running your application.

**Comment by stefanspelitz** [comment]
I am sorry, it seems I didn't make myself clear. I am using JDK 8 to launch Marathon and I am using Java 11 to launch my application.

The problem is that the VM arguments for my application (the ones mentioned above) are not accepted when launching it from within Marathon.

This issue is easy to reproduce: Just use any Java application, set `Java Home` to a JRE >= 9 and add any of the mentioned VM arguments to the VM arguments textbox in Marathon.

**Comment by ck-aditya** [comment]
Marathon sets the VM arguments as JAVA_TOOL_OPTIONS. But setting module path in JAVA_TOOL_OPTIONS is not supported by JDK-9+. This has been fixed in the upcoming Marathon Version.

**Comment by stefanspelitz** [comment]
Thank you for the information!
