### ISSUE TITLE
Selenium  removed RemoteWebDriver Constructors that take requiredCapabilities parameters

### ISSUE THREAD

**Issue by joe-fish** [jalian-systems/marathonv5#3]
The Selenium project has removed the constructors that take requiredCapabilities. The JavaDriver extends the RemoteWebDriver class and calls one of these constructors and passes a null in the requiredCapabilities parameter.  The JavaDriver needs to be updated to call one of the RemoteWebDriver constructors that still exist.  The link below is for the commit in the selenium github project.

https://github.com/SeleniumHQ/selenium/commit/05151a4aa10d795bc49f0027c5f8d35384abf55e#diff-fa76272f866d8067bb11a32f27773026

**Comment by kdmurthy** [comment]
We were using an earlier version of Selenium (3.0.1) for Marathon. We are upgrading and doing the necessary modifications and will release a new version soon.
