### ISSUE TITLE
Unable to Load Marathon Extensions

### ISSUE THREAD

**Issue by vaektor** [jalian-systems/marathonv5#4]
Marathon extensions are not loaded due to regular expression call to FindResources.findClasses

**Comment by kdmurthy** [comment]
Can you give more details?

1. Your extension class name should end with MarathonExtension
2. It should be added to classpath of marathon. Currently the scripts use '-jar' option where we can't add another jar. You need to modify them to use 'java -cp'. (We did this modification to marathonite, but missed in marathon)
3. The marathonite script adds UserLibs\* to classpath in marathonite installation folder. I suggest you do the same and copy your JAR file into UserLibs

-- KD

**Comment by vaektor** [comment]
Thank you. I was able to load the module after performing step #2.
