### ISSUE TITLE
Marathon cannot interact with a JTexfield in a JTabbedPane

### ISSUE THREAD

**Issue by paul-hammant** [jalian-systems/marathonv5#9]
Repo: https://github.com/paul-hammant/swing_component_testing

^ This repo is me preparing for a blog entry on MVC, and component testing. I intend it to be a showcase.

OK, so the problem is that Marathon isn't finding a visible field when it should do. All other tests in this project pass, including the same locate of text-field (and interactions with it), but when the field is in a second tab of a JTabbedPane, it isn't allowing sendKeys():

Line 62 - https://github.com/paul-hammant/swing_component_testing/blob/master/src/test/java/demo/WholeAppTests.java#L62 - does nothing when I expected it to.

**Comment by kdmurthy** [comment]
You need to get the tab and click on it. Something like:

secondTab = driver.find_element(:css, "tab-pane:nth-tab(2)");
secondTab.click();

Anyhow, I will download the repo later tonight and check it out.

**Comment by paul-hammant** [comment]
I guessed the same. I've done a setName("tab2") to make the locate of the tab easy. 

As it happens my tab's class in an inner class, and I don't think there's locators for class names ending in $1 and similar.   That is unless Marathon supports something like the following:

```
driver.find_element(:css, "sub-class-of-tab-pane::nth-tab(2)");
```
